version: '3'

volumes:
  data:

services:
  php7:
    build: .
    image: ${REPO_DOCKER}/php:7-fpm
    env_file:
      - .env
    volumes:
      - ../web:/project/html
      - ../logs/symfony:/project/html/var/logs:cached
      - ../tmp:/tmp

  bd:
    image: mariadb:10.3.7
    env_file:
      - .env
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql

  nginx:
    image: nginx:1.15
    volumes:
      - ../web:/project/html
      - ../logs/nginx:/var/log/nginx:cached
      - ./nginx.template:/etc/nginx/conf.d/default.conf
      #- ./nginx.template:/etc/nginx/conf.d/dev.template
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    env_file:
      - .env
    #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/dev.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    links:
      - php7:php


